format_version: v1.0
type: UniqueComponent
attributes: {id: evsys}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: EVSYS_CHANNEL_0_GENERATOR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '14'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_0_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'true'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_0_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'true'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_1_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_1_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_2_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_2_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_3_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_3_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_4_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_4_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_5_GENERATOR_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Boolean
    attributes: {id: EVSYS_CHANNEL_5_USER_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: evsys, value: 'false'}
  - type: Menu
    attributes: {id: EVSYS_MENU_0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: EVSYS_USER_11}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: EVSYS_USER_14}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Boolean
    attributes: {id: GENERATOR_EIC_EXTINT_4_ACTIVE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: 'true'}
  - type: Boolean
    attributes: {id: USER_TC2_EVU_READY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: 'true'}
- type: ElementPosition
  attributes: {x: '180', y: '20', id: evsys}
