files:
- generatedChecksum: E45D1648EFC10229D7BE94DB19221FF7
  logicalPath: config\sam_d11_xpro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E45D1648EFC10229D7BE94DB19221FF7
- generatedChecksum: 66E726B0174A7A23F123D966E5321271
  logicalPath: config\sam_d11_xpro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 66E726B0174A7A23F123D966E5321271
- generatedChecksum: 3AE56DC20F78A062104F3DA46D70F6E8
  logicalPath: config\sam_d11_xpro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3AE56DC20F78A062104F3DA46D70F6E8
- generatedChecksum: 6513F2461B8F476B68CA73906086047F
  logicalPath: config\sam_d11_xpro
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6513F2461B8F476B68CA73906086047F
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 4408A6F40B35CBC5233DC20C6FABAE4E
  logicalPath: config\sam_d11_xpro\peripheral\clock
  name: plib_clock.c
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4408A6F40B35CBC5233DC20C6FABAE4E
- generatedChecksum: EA86A70C07D2B93187AEB95D58F002F4
  logicalPath: config\sam_d11_xpro\peripheral\dac
  name: plib_dac.c
  physicalPath: peripheral\dac
  security: NON_SECURE
  type: SOURCE
  userChecksum: EA86A70C07D2B93187AEB95D58F002F4
- generatedChecksum: C16C00FF044063E443EF3CDCE4B17F50
  logicalPath: config\sam_d11_xpro\peripheral\dmac
  name: plib_dmac.c
  physicalPath: peripheral\dmac
  security: NON_SECURE
  type: SOURCE
  userChecksum: C16C00FF044063E443EF3CDCE4B17F50
- generatedChecksum: 990622D173D10DD6DDA2AAF4115227B0
  logicalPath: config\sam_d11_xpro\peripheral\evsys
  name: plib_evsys.c
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: SOURCE
  userChecksum: 990622D173D10DD6DDA2AAF4115227B0
- generatedChecksum: 69D3548A1C766EEC7C9C43CCA9512B0E
  logicalPath: config\sam_d11_xpro\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 69D3548A1C766EEC7C9C43CCA9512B0E
- generatedChecksum: E85A8757F82A322C86C52D9BF238E9E1
  logicalPath: config\sam_d11_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.c
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: SOURCE
  userChecksum: E85A8757F82A322C86C52D9BF238E9E1
- generatedChecksum: 4DB8719112123E419D5A35AA15BA06AE
  logicalPath: config\sam_d11_xpro\peripheral\port
  name: plib_port.c
  physicalPath: peripheral\port
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4DB8719112123E419D5A35AA15BA06AE
- generatedChecksum: 981CFBDC5B820D35E958C930828AF764
  logicalPath: config\sam_d11_xpro\peripheral\tc
  name: plib_tc1.c
  physicalPath: peripheral\tc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 981CFBDC5B820D35E958C930828AF764
- generatedChecksum: 2645E564BD945DAED1424FD8D7B39330
  logicalPath: config\sam_d11_xpro
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2645E564BD945DAED1424FD8D7B39330
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\sam_d11_xpro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 4DD9DBA759EF7DE2B25FFA72B25DDCD0
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: ac.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4DD9DBA759EF7DE2B25FFA72B25DDCD0
- generatedChecksum: E1B99CC25B1B91A0DEE836277D28A4FA
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E1B99CC25B1B91A0DEE836277D28A4FA
- generatedChecksum: 01B82424BC59A54620F7E9E0DB808EBB
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cachel1_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B82424BC59A54620F7E9E0DB808EBB
- generatedChecksum: 00A88E28C299A373117BC4D5B9E80C80
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 00A88E28C299A373117BC4D5B9E80C80
- generatedChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
- generatedChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang_ltm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
- generatedChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_compiler.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
- generatedChecksum: 42E8B722917508A3A9373D13AD827ED6
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_gcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E8B722917508A3A9373D13AD827ED6
- generatedChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_iccarm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
- generatedChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_version.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
- generatedChecksum: CCBD23918BE14943EA128B0D552031C5
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: core_cm0plus.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: CCBD23918BE14943EA128B0D552031C5
- generatedChecksum: 1D1E89E5594EE4FC269A9D502F04A4BA
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: dac.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D1E89E5594EE4FC269A9D502F04A4BA
- generatedChecksum: A9E90947A427CB0F171C53F135AA4B46
  logicalPath: config\sam_d11_xpro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: A9E90947A427CB0F171C53F135AA4B46
- generatedChecksum: 687144AAE1C845BFD766057C32B1BE14
  logicalPath: config\sam_d11_xpro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 687144AAE1C845BFD766057C32B1BE14
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config\sam_d11_xpro
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: 02116234C47B627FCC09973CB703E89E
  logicalPath: config\sam_d11_xpro
  name: device_vectors.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 02116234C47B627FCC09973CB703E89E
- generatedChecksum: C0A96DDBC894A73CAA8493B832DCE172
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: dmac.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C0A96DDBC894A73CAA8493B832DCE172
- generatedChecksum: 9CD6896C4584CB0CD2EB1CB4BFF679CE
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: dsu.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9CD6896C4584CB0CD2EB1CB4BFF679CE
- generatedChecksum: 714CFEAD5DEFE1FC12938565CA191502
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: eic.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 714CFEAD5DEFE1FC12938565CA191502
- generatedChecksum: AD996FC2C09B7A77436F67D4C6D71ADD
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: evsys.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: AD996FC2C09B7A77436F67D4C6D71ADD
- generatedChecksum: 642C03C9EEE3F771393405FE4603F24B
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: gclk.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 642C03C9EEE3F771393405FE4603F24B
- generatedChecksum: 5A6D893A2F207140E84ABAB17DC8B5DB
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: hmatrixb.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5A6D893A2F207140E84ABAB17DC8B5DB
- generatedChecksum: 53551D5FE5CE73E15107B1AD7D845B4A
  logicalPath: config\sam_d11_xpro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 53551D5FE5CE73E15107B1AD7D845B4A
- generatedChecksum: B96ADDA2C111E73B26EBA5E7B4498912
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: mpu_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: B96ADDA2C111E73B26EBA5E7B4498912
- generatedChecksum: 4D95F71D71F0A56D9ED955A1B790BF7B
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: mtb.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4D95F71D71F0A56D9ED955A1B790BF7B
- generatedChecksum: 2E0CDE2EFB6FDAC165B5DCA2DCB79327
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: nvmctrl.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 2E0CDE2EFB6FDAC165B5DCA2DCB79327
- generatedChecksum: 9AA552EAC09D968E3E6EA5F42B2D40A1
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: pac.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9AA552EAC09D968E3E6EA5F42B2D40A1
- generatedChecksum: A170879AEE6FB32A02A41B532A05A447
  logicalPath: config\sam_d11_xpro\peripheral\clock
  name: plib_clock.h
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: HEADER
  userChecksum: A170879AEE6FB32A02A41B532A05A447
- generatedChecksum: 9290D4A79F86C3A3D1E5CE508A1A0DF4
  logicalPath: config\sam_d11_xpro\peripheral\dac
  name: plib_dac.h
  physicalPath: peripheral\dac
  security: NON_SECURE
  type: HEADER
  userChecksum: 9290D4A79F86C3A3D1E5CE508A1A0DF4
- generatedChecksum: 360C1CC6E1F380898A539EF3BE8BE5B4
  logicalPath: config\sam_d11_xpro\peripheral\dmac
  name: plib_dmac.h
  physicalPath: peripheral\dmac
  security: NON_SECURE
  type: HEADER
  userChecksum: 360C1CC6E1F380898A539EF3BE8BE5B4
- generatedChecksum: CCAEF942C66AF995876DFD85CEFF611F
  logicalPath: config\sam_d11_xpro\peripheral\evsys
  name: plib_evsys.h
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: HEADER
  userChecksum: CCAEF942C66AF995876DFD85CEFF611F
- generatedChecksum: 55ECCC7FA71BD15B46EF80DC0515ED7A
  logicalPath: config\sam_d11_xpro\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: 55ECCC7FA71BD15B46EF80DC0515ED7A
- generatedChecksum: DD0B8CA91B291923DFE1D0919C37D7CE
  logicalPath: config\sam_d11_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.h
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: HEADER
  userChecksum: DD0B8CA91B291923DFE1D0919C37D7CE
- generatedChecksum: 49FA518921664BC9FBC08A3B2A2BA271
  logicalPath: config\sam_d11_xpro\peripheral\port
  name: plib_port.h
  physicalPath: peripheral\port
  security: NON_SECURE
  type: HEADER
  userChecksum: 49FA518921664BC9FBC08A3B2A2BA271
- generatedChecksum: 5A897C1B5D3DD24FC9979C41DDDA6DFF
  logicalPath: config\sam_d11_xpro\peripheral\tc
  name: plib_tc1.h
  physicalPath: peripheral\tc
  security: NON_SECURE
  type: HEADER
  userChecksum: 5A897C1B5D3DD24FC9979C41DDDA6DFF
- generatedChecksum: 6DBEAF7BD42014F5492374805406687A
  logicalPath: config\sam_d11_xpro\peripheral\tc
  name: plib_tc_common.h
  physicalPath: peripheral\tc
  security: NON_SECURE
  type: HEADER
  userChecksum: 6DBEAF7BD42014F5492374805406687A
- generatedChecksum: CF4E7113CFA90E0E0B7F06FC9730AFE8
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: pm.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: CF4E7113CFA90E0E0B7F06FC9730AFE8
- generatedChecksum: 9F9E6DD3465FBDA1F06C3B55888F5352
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: port.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9F9E6DD3465FBDA1F06C3B55888F5352
- generatedChecksum: 667C79C2C8EDEAA14FF30B7A52CE96F0
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: ptc.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 667C79C2C8EDEAA14FF30B7A52CE96F0
- generatedChecksum: 7A78E895A6FAA7C4097AD69AF1D35310
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7A78E895A6FAA7C4097AD69AF1D35310
- generatedChecksum: B927EC73044D7BA6A9B8E3778CB11769
  logicalPath: packs\ATSAMD11D14AM_DFP
  name: samd11d14am.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: B927EC73044D7BA6A9B8E3778CB11769
- generatedChecksum: 82209625ED73379C4A6053BF3254B514
  logicalPath: packs\ATSAMD11D14AM_DFP\pio
  name: samd11d14am.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: 82209625ED73379C4A6053BF3254B514
- generatedChecksum: 0FF1D283F2F0858A158B569EFE2AD049
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: sercom.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 0FF1D283F2F0858A158B569EFE2AD049
- generatedChecksum: 9B7EC9BF1EADF4CB6C6AFFB0D2F48F96
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: sysctrl.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9B7EC9BF1EADF4CB6C6AFFB0D2F48F96
- generatedChecksum: CECF410F86CB5F14CC1B703DFB26080F
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: CECF410F86CB5F14CC1B703DFB26080F
- generatedChecksum: EDBCDE8C947DB3E66655F87A2B456BA4
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: tcc.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: EDBCDE8C947DB3E66655F87A2B456BA4
- generatedChecksum: 20E829A99B86C2889E4E2E536161C27A
  logicalPath: config\sam_d11_xpro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E829A99B86C2889E4E2E536161C27A
- generatedChecksum: 87393BF9ECA53228BFD27FC578294183
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: usb.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 87393BF9ECA53228BFD27FC578294183
- generatedChecksum: 7ACDFC92FD15ECFBF7D14D1E2E6A4A9F
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7ACDFC92FD15ECFBF7D14D1E2E6A4A9F
- generatedChecksum: 87035D53A3764E99348B89DDBF84AD9D
  logicalPath: config\sam_d11_xpro
  name: ATSAMD11D14AM.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 87035D53A3764E99348B89DDBF84AD9D
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d11_xpro;../src/packs/ATSAMD11D14AM_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d11_xpro;../src/packs/ATSAMD11D14AM_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
