configName: sam_d11_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMD11D14AM
projectName: ''
settings:
  PackageFilter: csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.5.1
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMD11_DFP\2.0.9\atdf\ATSAMD11D14AM.atdf
